Got a bluescreen in windows while cloning a mercurial repository.After reboot, I now get this message for almost all hg commands:Google is no help.Any tips?When "waiting for lock on repository", delete the repository file: .hg/store/lockWhen  deleting the lock file, you must make sure nothing else is accessing the repository. (If the lock is a string of zeros, this is almost certainly true).When waiting for lock on working directory, delete .hg/wlock.Coworker had this exact problem today, after a BSoD while trying to push. He had to:Then his repo worked again.EDIT: As per @Marmoute\'s comment - when dealing with lock-related issues, using hg debuglock is a safer alternative to blindly deleting the .hg/store/lock file.I am very familiar with Mercurial\'s locking code (as of 1.9.1). The above advice is good, but I\'d add that:(For the curious: I haven\'t yet been able to catch the cause of this problem, but suspect it\'s either an older version of Mercurial accessing the repository or a problem in Python\'s socket.gethostname() call on certain versions of Windows.)I had this problem with no detectable lock files.  I found the solution here: http://schooner.uwaterloo.ca/twiki/bin/view/MAG/HgLockErrorHere is a transcript from Tortoise Hg Workbench consoleAfter this the aborted pull ran sucessfully.The lock had been set more than 2 years ago, by a process on a machine that is no longer on the LAN.  Shame on the hg developers for a) not documenting locks adequately; b) not timestamping them for automatic removal when they get stale.I had the same problem on Win 7. \nThe solution was to remove following files: As for .hg/store/lock  - there was no such file.If the locked repo was the original, I can\'t imagine it was modifying it to clone it, so it was only preventing you from changing it in the middle and messing up the clone. It should be fine after removing the lock.The new cloned copy (if it was a local clone) could be in any sort of malformed state, though, so you should throw it out and start it over. (If it was a remote clone, I would hope it failed and already threw out the incomplete copy.)I do not expect this to be a winning answer, but it is a fairly unusual situation.\nMentioning in case someone other than me runs into it.Today I got the "waiting for lock on repository" on an hg push command.When I killed the hung hg command I could see no .hg/store/lockWhen I looked for .hg/store/lock while the command was hung, it existed. But the lockfile was deleted when the hg command was killed.When I went to the target of the push, and executed hg pull, no problem.Eventually I realized that the process ID on the hg push was lock waiting message was changing each time. It turns out that the "hg push" was hanging waiting for a lock held by itself (or possibly a subprocess, I did not investigate further).It turns out that the two workspaces, let\'s call them A and B, had .hg trees shared by symlink:This is NOT a good thing to do with Mercurial.  Mercurial does not understand the concept of two workspaces sharing the same repository. I do understand, however, how somebody coming to Mercurial from another VCS might want this  (Perforce does, although not a DVCS; the Bazaar DVCS reportedly can do so). I am surprised that a symlinked REP-ROOT/.hg works at all, although it seems to except for this push.If it only happens on mapped drives it might be bug https://bitbucket.org/tortoisehg/thg/issue/889/cant-commit-file-over-network-share. Using UNC path instead of drive letter seems to sidestep the issue.I encountered this problem on Mac OS X 10.7.5 and Mercurial 2.6.2 when trying to push.  After upgrading to Mercurial 3.2.1, I got "no changes found" instead of "waiting for lock on repository".  I found out that somehow the default path had gotten set to point to the same repository, so it\'s not too surprising that Mercurial would get confused.