Does anyone know whether there is an assert or something like that which can test whether an exception was thrown in the code being tested?http://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.exceptions.examples.ExceptionTest.phpYou can also use a docblock annotation:For PHP 5.5+ (especially with namespaced code), I now prefer using ::classIf you\'re running on PHP 5.5+, you can use ::class resolution to obtain the name of the class with expectException/setExpectedException. This provides several benefits:Example:PHP compilesintowithout PHPUnit being the wiser.Note: PHPUnit 5.2 introduced expectException as a replacement for setExpectedException.Code below will test exception message and exception code. Important: It will fail if expected exception not thrown too.You can use assertException extension to assert more than one exception during one test execution.Insert method into your TestCase and use:I also made a trait for lovers of nice code..An alternative way can be the follwing:Please ensure that your test class extents \\PHPUnit_Framework_TestCaseHere\'s all the exception assertions you can do.  Note that all of them are optional.Documentation can be found here.Be very carefull about "/**", notice the double "*". Writing only "**"(asterix) will fail your code.\nAlso make sure your using last version of phpUnit. In some earlier versions of phpunit @expectedException Exception is not supported. I had 4.0 and it didn\'t work for me, I had to update to 5.5 https://coderwall.com/p/mklvdw/install-phpunit-with-composer to update with composer.